version: '3.8'
services:
  webapi:
    image: 192.168.1.21:5000/homeserver-webapi:latest
    ports:
      - "8081:80"
    volumes:
      - ./secrets.json:/app/secrets.json
      - ./logs:/app/logs
    restart: always

  webpage:
    image: 192.168.1.21:5000/homeserver-webpage:latest
    ports:
      - "8080:80"
    restart: always